### PR TITLE
Update pre-request.js

### PR DESCRIPTION
**Pull request by veracode-dmedeiros**
Modified code to inject in authorization header without need of global variable

### CODE REVIEW

**Comment by relaxnow** [comment]
@dmedeiros-veracode `Veracode Example.postman_collection.json` should also be updated because that's the thing that will be imported into postman. The .js file is just there for reference I think.

**Comment by tjarrettveracode** [comment]
@dmedeiros-veracode and @relaxnow -- I think these changes look good as far as the code goes. You've added the relevant API creds fields into the environment file and added error handling, as far as I can tell. Can one of you please also update the `README.md` with any appropriate changes for setup?

**Comment by relaxnow** [comment]
@dmedeiros-veracode could you move the code to the JSON file and update the README?

**Comment by veracode-dmedeiros** [comment]
@tjarrettveracode this pull request is waiting on your review to move forward

**Comment by tjarrettveracode** [comment]
@dmedeiros-veracode -- did you address the comments regarding the need to update the README file? I don't see that in the list of changes on this merge request.

**Comment by veracode-dmedeiros** [comment]
Providing a different pull request with Updated Readme and confirmed fixes

**Pull request closed without merging**
